### ISSUE TITLE
Make a repository that contains a docker-compose file that bring everything up

### ISSUE THREAD

**Issue by fizk** [fizk/Loggjafarthing#18]
Create a dev repo that will run all these services configured and what not.

These are the system (and satellite systems).

* [x] Thumbor
* [ ] ~Logstash~ (Will be done later)
* [ ] Master (load balancer)
* [x] [GraphQL /  Isomorphic](https://github.com/fizk/AlthingiQL)
* [x] API ([Loggjafarthing](https://github.com/fizk/Loggjafarthing))
    * [x] MySQL
    * [x] Elastic Search
    * [x] Redis
* [x] Aggregator ([AlthingiAggregator](https://github.com/fizk/AlthingiAggregator))
    * [x] Redis

#### API ([Loggjafarthing](https://github.com/fizk/Loggjafarthing))
* [x] Build an Apache/PHP image
    * [ ] ~Configure Apache (.htaccess)~
    * [x] Configure PHP (php.ini)
        * [x] Install extensions
* [x] Attache MySQL
    * [x] Configure MySQL
* [x] Attache ElasticSearch
    * [x] Configure ElasticSearch
* [x] Attache Redis
    * [x] Configure Redis
* [x] Mount **code** to volume
* [x] Run `compose install`
* [x] Start Apache on port 80
    * [x] Expose port 8080
* [x] Write logs to disk
* [x] Environment variables for all services

#### Aggregator ([AlthingiAggregator](https://github.com/fizk/AlthingiAggregator))
* [x] Build an PHP image
    * [x] Configure PHP (php.ini)
        * [x] Install extensions
* [x] Attache Redis
    * [x] Configure Redis
* [x] Mount **code** to volume
* [x] Write logs to disk
* [x] Environment variables for all services
* [ ] ~Make so that the images accepts ARGs for which script to run~ (later)

#### [GraphQL /  Isomorphic](https://github.com/fizk/AlthingiQL)
* [x] Build an Node image
* [x] Install npm etc...
* [x] Attach to ([API](https://github.com/fizk/Loggjafarthing))
* [x] Mount **code** to volume
* [x] Build code
    * [x] `npm install`
    * [x] Inject env.vars so the code has the right values
    * [x] Build client code (Webpack)
    * [x] Build server code (tsc)
* [ ] ~Write logs to disk~ (later)
* [x] Environment variables for all services
* [x] Start Express on port 3000

## CI
* [ ] Aggregator ([AlthingiAggregator](https://github.com/fizk/AlthingiAggregator)) Travis
* [x] API ([Loggjafarthing](https://github.com/fizk/Loggjafarthing)) Travis
