### ISSUE TITLE
Feed in temporary documents

### ISSUE THREAD

**Issue by fizk** [fizk/Loggjafarthing#20]
Feed in temporary documents 

https://www.althingi.is/xml/145

Available:

* lidaskjol
* fundir
* fjarvist
* dagskra
* raedur_bradabirgda
* utbyting
* raedur
* inn
* lestrarsalur

For this iteration... only **raedur_bradabirgda** will be fetched

**API** https://github.com/fizk/Loggjafarthing/projects/1#card-18322157

* [x] Controller (for temp speeches)
    * [x] Test
* [x] Extractor
    * [x] Update Test Seed data
* [x] Data - add `isValidated` flag

**Aggregator** https://github.com/fizk/Loggjafarthing/projects/1#card-18322156
* [x] Hydrator
    * [x] Accept `isValidated` flag
* [x] Form
    * [x] Accept `isValidated` flag
* [x] Database
    * [x] Accept `isValidated` flag
